# Generated by Django 4.2.6 on 2023-10-29 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review_buku', '0002_rename_posted_at_review_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='gambar',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='judul',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='penulis',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='returned',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='tahun',
        ),
        migrations.AlterField(
            model_name='buku',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
